# manager.conf - 脚本管理器选项配置
# 放置路径: script-opts/manager.conf

# OSD 界面字体（可修改为你本地支持的字体，例如中文字体防乱码：Microsoft YaHei, PingFang SC 等）
osd_font=Sans

# 标题字体大小
osd_font_size_title=22

# 详细状态字体大小
osd_font_size_detail=18

# 弹窗在 1280x720 虚拟画布下的 X 轴起点坐标
osd_pos_x=330

# 弹窗在 1280x720 虚拟画布下的 Y 轴起点坐标（默认 64 处于屏幕上方）
osd_pos_y=64

# 弹窗总宽度（像素）
osd_width=620

# 弹窗总高度（像素）
osd_height=96