# profile-chain.conf
# 链头=profile1,profile2
# 链头.trigger=property1,property2
#
# 常用 trigger 属性：
#   video-params/w, video-params/h       分辨率
#   video-params/average-bpp             位深
#   video-params/max-luma                HDR 亮度
#   video-params/primaries               色域
#   video-params/gamma                   传输函数
#   current-tracks/video/id              视频轨
#   current-tracks/audio/lang            音频语言
#   path                                 文件路径
#   filename                             文件名
#   speed                                播放速度
#   pause                                暂停状态

Base=SD,Deband,HDR
Base.trigger=video-params/w,video-params/h,current-tracks/video/id
