# 指定是否启用脚本功能，默认值：yes
#! 注意该选项可在运行中更改
enabled=yes

# 指定 uosc 插件脚本 recentmenu 保存的最近播放记录的文件路径。可以是 mpv 支持的相对路径或绝对路径
path=~~/files/recent.json

# 指定打开脚本菜单时显示的菜单标题
title=近期播放

# 指定最近播放记录的保存条目的最大数量。默认值：20
length=20

# 指定 uosc 的最近播放记录的菜单条目的字符数限制。默认值：70
width=70

# 是否只记录同目录下的相同系列文件的最后播放条目。默认：yes
ignore_same_series=yes

# 是否在每次加载视频时同步检查历史文件是否已被删除/失效。
# 默认值：no（强烈建议保持 no，开启后如果历史记录里包含网盘、休眠硬盘或网络共享盘，切换时会引起严重的卡顿或假死）
check_deleted=no
